# Generated by Django 3.1.3 on 2020-11-13 00:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('BussinessName', models.CharField(max_length=80, verbose_name='Razón Social')),
                ('Ruc', models.CharField(max_length=13, verbose_name='Razón Social')),
                ('Phone', models.CharField(max_length=80, verbose_name='Telefono')),
                ('Email', models.EmailField(max_length=80, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('DateOrder', models.DateField(default=django.utils.timezone.now)),
                ('WeekOrder', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semana Orden')),
                ('DelieverOrder', models.DateField(blank=True, null=True)),
                ('Delivery', models.BooleanField(default=False)),
                ('TotalPay', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ProviderId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compras',
            },
        ),
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('Quantity', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.order', verbose_name='Orden de Compra')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle Pedido de Compra',
                'verbose_name_plural': 'Detalles de Pedidos de Compra',
            },
        ),
    ]
