# Generated by Django 3.1.3 on 2020-11-13 00:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('Names', models.CharField(max_length=80, verbose_name='Nombres')),
                ('SurNames', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('IdentificationCard', models.CharField(max_length=10, verbose_name='Cédula')),
                ('City', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('Address', models.CharField(blank=True, max_length=120, null=True, verbose_name='Dirección')),
                ('Phone', models.CharField(max_length=88, verbose_name='Telefono')),
                ('Email', models.EmailField(max_length=200, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('Names', models.CharField(max_length=80, verbose_name='Nombres')),
                ('SurNames', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('IdentificationCard', models.CharField(max_length=10, verbose_name='Cédula')),
                ('Birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('City', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('Address', models.CharField(max_length=120, verbose_name='Dirección')),
                ('Phone', models.CharField(max_length=88, verbose_name='Telefono')),
                ('Email', models.EmailField(max_length=200, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('DateInvoice', models.DateField(default=django.utils.timezone.now)),
                ('WeekInvoice', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semana Factura')),
                ('SubTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('TotalPay', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('Discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('Num_Porcent_Des', models.IntegerField(blank=True, null=True)),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.client', verbose_name='Cliente')),
                ('SellerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.seller', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='DetailInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('Quantity', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Utility', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('InvoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.invoice', verbose_name='Factura')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle Factura',
                'verbose_name_plural': 'Detalles de Factura',
            },
        ),
    ]
