# Generated by Django 3.1.3 on 2020-12-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='StatusInvoice',
            field=models.IntegerField(blank=True, choices=[(1, 'Solicitado'), (2, 'Entregado'), (3, 'Pagado')], null=True),
        ),
    ]
